kernelList = {
              "dense": "Dense",
              # "dense_ns": "SparseMMVecAccum_noSort",
              # "dense_sortMat": "SparseMMVecAccum_sortMat",
              "hash": "Hash",
              "heap": "Heap",
              # "merge": "Merge",
              "merge": "MergeOpt",
            #   "timOpt": "SparseMMTimOptimized",
            #   "timVecOpt": "SparseMMTimOptimizedSpSp",
              "eigen":"Eigen",
            #   "yuheap":"SparseMMExternalYuHeap",
            #   "yuhash":"SparseMMExternalYuHash",
              # "yuhash-ns":"SparseMMExternalYuHash-NoSort",
            #   "yuhashvec":"SparseMMExternalYuHashVec",
              # "yuhashvec-ns":"SparseMMExternalYuHashVec-NoSort",
              }